#page title
page_title                                : Bills io                                  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1499730119                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free Forever, Premium $9.99 / Year                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Bills io, the secure expense manager

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nathan Grey                                
your_link                                 : https://github.com/overtfuture            
your_city                                 : Washington D.C.                                
email_address                             : contact@studioember.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : billsioapp
github_username                           : studioember
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Encrypted, private, and secure
    description                           : No trackers, analytics, or linking bank accounts. Your data is yours, stored and accessed from iCloud. 
    fontawesome_icon_name                 : lock
    
  - title                                 : Fully Functioning Free Tier
    description                           : Tracking expenses shouldn't cost money. The free tier is fully capable of managing a basic budget. 
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Set & Remember
    description                           : Monthly, weekly, annually, or how about a combination of any type of repeating reminder?
    fontawesome_icon_name                 : bookmark

  - title                                 : Account Based Tracking
    description                           : Know exactly how much gets charged to your credit card for those auto-renewing subscriptions
    fontawesome_icon_name                 : credit-card
    
  - title                                 : Bill Overview
    description                           : Quickly calculate your monthly costs, including bills that occur more or less frequent than monthly
    fontawesome_icon_name                 : brain
    
  - title                                 : iPhone, iPad, and macOS Apps
    description                           : Check your Bills from any Apple device, all with native support
    fontawesome_icon_name                 : mobile



# Theme Settings
topbar_color                              : "#01003d"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.3

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#fafafa"

link_color                                : "#130691"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#01003d"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#0fead9"
feature_icons_background_color            : "#01003d"

social_icons_foreground_color             : "#a444e2"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown